# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInstagram', '0004_auto_20160405_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_time']},
        ),
    ]
