# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInstagram', '0006_auto_20160412_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_time']},
        ),
    ]
