# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInstagram', '0007_auto_20160412_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
