# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 05:23
from __future__ import unicode_literals

import MyInstagram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInstagram', '0008_auto_20160413_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=MyInstagram.models.get_unique_photo_name),
        ),
    ]
