# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInstagram', '0009_auto_20160428_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=150, unique=True, verbose_name='email address'),
        ),
    ]
